# Generators in Python

import sys
import time

# Define a generator function that yields squares of numbers up to a given limit
def myGenerator(number):
    for i in range(number):
        yield i ** 2

# Define an infinite sequence generator
def infinite_sequence():
    result = 1
    while True:
        # Yield the result before performing the next operation
        yield result
        # Perform operation: multiply the result by 10 for the next iteration
        result *= 10

# Iterate through the range 0 to 11
for x in range(0, 12):
    # Create a generator object 'values' using 'myGenerator' for each 'x' in the range
    values = myGenerator(x)
    
    # Iterate through the 'values' generated by 'myGenerator(x)' and print them
    for value in values:
        print(value, end=" ")  # Print each value separated by a space
    print(" ")  # Print a new line after printing all values
    
    time.sleep(0.25)  # Pause the execution for 0.25 seconds

# Create an object 'sequence' which is an instance of the 'infinite_sequence' generator
sequence = infinite_sequence()

# Print the next four values generated by the 'infinite_sequence' generator using 'next()'
print(next(sequence), next(sequence), next(sequence), next(sequence))
